#define GG(x)     sub(gg, ':', ':', x)
#define EE(x)     sub(ee, ':', ':', x)
#define A(x)      sub(a,  ':', ':', x)
#define AAM(x)    sub(aam,  ':', ':', x)
#define C(x)      sub(c,  ':', ':', x)
#define KM(x)     sub(km,  ':', ':', x)
#define VF(x)     sub(vf, ':', ':', x)
#define VB(x)     sub(vb, ':', ':', x)
#define UF(x)     sub(uf, ':', ':', x)
#define UB(x)     sub(ub, ':', ':', x)
#define F(x)      sub(f, ':', ':', x)
#define RAD(x)    sub(rad, ':', ':', x)
#define Q2F(x)    sub(q2f, ':', ':', x)
#define Q2LF(x)   sub(q2lf, ':', ':', x)
#define L(x)      sub(l, ':', ':', x)
#define L0(x)     sub(l0, ':', ':', x)
#define DTEF(x)   sub(dtef, ':', ':', x)
#define KN(x)     sub(kn, ':', ':', x)
#define DZ(x)     sub(dz, ':',':',x)
#define DZZ(x)    sub(dzz, ':',':',x)
